apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

resources:
- agent-flow-mixin/deploy/manifests/k8s-all-in-one.yaml
- go-runtime-mixin/deploy/manifests/k8s-all-in-one.yaml
- loki-mixin/deploy/manifests/k8s-all-in-one.yaml
- mimir-mixin/deploy/manifests/k8s-all-in-one.yaml
- tempo-mixin/deploy/manifests/k8s-all-in-one.yaml
