 # Based on information on https://opentelemetry.io/docs/collector/configuration/
receivers:
  # Data sources: traces, metrics, logs
  otlp: # Allow sending data via OTLP protocol
    protocols:
      http:

  # Data sources: metrics
  prometheus: # Scrape self
    config:
      scrape_configs:
        - job_name: otel-collector-remote-write
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:8888]
              labels:
                scraped_by: otel-collector-remote-write
        - job_name: mimir
          static_configs:
            - targets: ['mimir']
              labels:
                scraped_by: otel-collector-remote-write

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://grafana-agent-cluster:12345/api/v1/push
  otlp:
    endpoint: http://grafana-agent-cluster:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite, otlp]