apiVersion: 1

datasources:
# Mimir for metrics
- name: Metrics
  type: prometheus
  uid: metrics
  access: proxy
  orgId: 1
  url: http://gateway:8080/prometheus
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: traces
        
- name: Mimir Alertmanager
  uid: alertmanager
  type: alertmanager
  access: proxy
  orgId: 1
  url: http://gateway:8080/alertmanager
  version: 1
  editable: true


# Loki for logs
- name: Logs
  type: loki
  access: proxy
  orgId: 1
  uid: logs
  url: http://gateway:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    derivedFields:
      - datasourceUid: traces
        matcherRegex: traceID=(\w+)
        name: TraceID
        url: $${__value.raw}


# Tempo for traces
- name: Traces
  type: tempo
  access: proxy
  orgId: 1
  uid: traces
  url: http://gateway:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  jsonData:
    lokiSearch:
      datasourceUid: logs
    nodeGraph:
      enabled: true
    serviceMap:
      datasourceUid: metrics
    tracesToLogsV2:
      customQuery: false
      datasourceUid: logs


# Pyroscope for profiles
- name: Profiles
  type: phlare
  access: proxy
  orgId: 1
  uid: profiles
  url: http://pyroscope:4040
  basicAuth: false
  isDefault: false
  version: 1
  editable: true