analytics:
  reporting_enabled: false

storage:
  backend: s3
  s3:
    bucket_name: pyroscope-data
    endpoint: minio:9000
    access_key_id: acester822
    secret_access_key: 228retseca
    insecure: true
