version: '3.9'

services:
  agent: # All
    depends_on:
      gateway:
        condition: service_healthy
    image: grafana/agent:v0.37.2
    volumes:
      - /mnt/Media/Monitoring/Configs/agent-flow:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent
      - run
      - /etc/agent-config/
      - --server.http.listen-addr=0.0.0.0:12345
      - --cluster.enabled=true
      - --cluster.join-addresses=grafana-agent-cluster:12345
      - --disable-reporting=true
    environment:
      - AGENT_MODE=flow
      - AGENT_CONFIG_FOLDER=/etc/agent-config
    healthcheck:
      disable: true
    ports:
      - "12345"
    # scale up support
    deploy:
      replicas: 2
    networks:
      default:
        aliases:
          - grafana-agent-cluster
  minio: # All
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/mimir-data /data/mimir-rules /data/mimir-alertmanager && \
        mkdir -p /data/loki-data /data/loki-rules && \
        mkdir -p /data/tempo-data  && \
        mkdir -p /data/pyroscope-data && \
        minio server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin_password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
      - MINIO_PROMETHEUS_URL="http://gateway:8500/prometheus"
      - MINIO_PROMETHEUS_JOB_ID="integrations/minio"
    volumes:
      - /mnt/Media/Monitoring/Data:/data:delegated
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9001:9001"

  gateway: # All
    depends_on:
      mimir-write:
        condition: service_healthy
      mimir-backend:
        condition: service_healthy
    image: nginxinc/nginx-unprivileged:1.25-alpine
    volumes:
      - /mnt/Media/Monitoring/Configs/nginx:/etc/nginx/templates
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - DISTRIBUTOR_HOST=mimir-write
      - QUERY_FRONTEND_HOST=mimir-read
      - ALERT_MANAGER_HOST=mimir-backend
      - RULER_HOST=mimir-backend
      - COMPACTOR_HOST=mimir-backend
      - LOKI_DISTRIBUTOR_HOST=loki-write
      - LOKI_INGESTER_HOST=loki-write
      - LOKI_RULER_HOST=loki-backend
      - LOKI_QUERY_FRONTEND_HOST=loki-read
      - LOKI_QUERY_SCHEDULER_HOST=loki-read
      - LOKI_QUERIER_HOST=loki-read
      - LOKI_COMPACTOR_HOST=loki-backend
      - TEMPO_DISTRIBUTOR_HOST=tempo-distributor
      - TEMPO_INGESTER_HOST=tempo-ingester
      - TEMPO_QUERY_FRONTEND_HOST=tempo-frontend
      - TEMPO_COMPACTOR_HOST=tempo-compactor
      - PYRO_DISTRIBUTOR_HOST=pyro-distributor
      - PYRO_QUERY_FRONTEND_HOST=pyro-frontend
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8500/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8500" # Mimir
      - "3100" # Loki
      - "3200" # Tempo
      - "4317" # Tempo
      - "4040" # Pyro

  mimir-backend: # Metrics
    depends_on:
      minio:
        condition: service_healthy
    image: &mimirImage grafana/mimir:2.10.3
    command:
      - -config.file=/etc/mimir.yaml
      - -target=backend
    volumes:
      - /mnt/Media/Monitoring/Configs/mimir/read-write-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use read-write-mode-metrics.yaml
      - /mnt/Media/Monitoring/Configs/mimir:/etc/mimir
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8500/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 2

  mimir-read: # Metrics
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    command:
      - -config.file=/etc/mimir.yaml
      - -target=read
    volumes:
      - /mnt/Media/Monitoring/Configs/mimir/read-write-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use read-write-mode-metrics.yaml
      - /mnt/Media/Monitoring/Configs/mimir:/etc/mimir
    deploy:
      replicas: 2

  mimir-write: # Metrics
    depends_on:
      minio:
        condition: service_healthy
    image: *mimirImage
    command:
      - -config.file=/etc/mimir.yaml
      - -target=write
    volumes:
      - /mnt/Media/Monitoring/Configs/mimir/read-write-mode-metrics.yaml:/etc/mimir.yaml # Note: Mimir use read-write-mode-metrics.yaml
      - /mnt/Media/Monitoring/Configs/mimir:/etc/mimir
    ports:
      - "8500"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8500/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - mimir-memberlist

  loki-read: # Loki
    depends_on:
      minio:
        condition: service_healthy
    image: &lokiImage grafana/loki:2.9.2
    command:
      - -config.file=/etc/loki.yaml
      - -target=read
      - -legacy-read-mode=false
      - -log.level=warn
    volumes:
      - /mnt/Media/Monitoring/Configs/loki/read-write-mode-logs.yaml:/etc/loki.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 2
    networks:
      default:
        aliases:
          - loki-memberlist

  loki-write: # Loki
    depends_on:
      minio:
        condition: service_healthy
    image: *lokiImage
    command:
      - -config.file=/etc/loki.yaml
      - -target=write
    volumes:
      - /mnt/Media/Monitoring/Configs/loki/read-write-mode-logs.yaml:/etc/loki.yaml
    ports:
      - "3100"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - loki-memberlist

  loki-backend: # Loki
    depends_on:
      minio:
        condition: service_healthy
    image: *lokiImage
    deploy:
      replicas: 2
    command:
      - -config.file=/etc/loki.yaml
      - -target=backend
      - -legacy-read-mode=false
    volumes:
      - /mnt/Media/Monitoring/Configs/loki/read-write-mode-logs.yaml:/etc/loki.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tempo-distributor: # Tempo
    depends_on:
      tempo-ingester:
        condition: service_started
    image: &tempoImage grafana/tempo:2.2.3
    volumes:
      - /mnt/Media/Monitoring/Configs/tempo/microservices-mode-traces.yaml:/etc/tempo.yaml # Note: Tempo use microservices-mode-traces.yaml
    command:
      - -config.file=/etc/tempo.yaml
      - -target=distributor
      # - -log.level=warn
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3200/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tempo-ingester: # Tempo
    depends_on:
      minio:
        condition: service_healthy
    image: *tempoImage
    volumes:
      - /mnt/Media/Monitoring/Configs/tempo/microservices-mode-traces.yaml:/etc/tempo.yaml # Note: Tempo use microservices-mode-traces.yaml
    ports:
      - "3200"
    command:
      - -config.file=/etc/tempo.yaml
      - -target=ingester
      - -log.level=warn
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - tempo-memberlist

  tempo-frontend: # Tempo
    depends_on:
      minio:
        condition: service_healthy
    image: *tempoImage
    volumes:
      - /mnt/Media/Monitoring/Configs/tempo/microservices-mode-traces.yaml:/etc/tempo.yaml # Note: Tempo use microservices-mode-traces.yaml
    command:
      - -config.file=/etc/tempo.yaml
      - -target=query-frontend
      - -log.level=warn

  tempo-querier: # Tempo
    depends_on:
      minio:
        condition: service_healthy
    image: *tempoImage
    volumes:
      - /mnt/Media/Monitoring/Configs/tempo/microservices-mode-traces.yaml:/etc/tempo.yaml # Note: Tempo use microservices-mode-traces.yaml
    command:
      - -config.file=/etc/tempo.yaml
      - -target=querier
      - -log.level=warn

  tempo-compactor: # Tempo
    depends_on:
      minio:
        condition: service_healthy
    image: *tempoImage
    volumes:
      - /mnt/Media/Monitoring/Configs/tempo/microservices-mode-traces.yaml:/etc/tempo.yaml # Note: Tempo use microservices-mode-traces.yaml
    command:
      - -config.file=/etc/tempo.yaml
      - -target=compactor
      - -log.level=error

  pyro-distributor: # Pyro
    depends_on:
      pyro-ingester:
        condition: service_started
    image: &pyroscopeImage grafana/pyroscope:1.1.5
    volumes:
      - /mnt/Media/Monitoring/Configs/pyro/microservices-mode-profiles.yaml:/etc/config.yaml # Note: profiles use microservices-mode-profiles.yaml
    ports:
      - "4040"
    command:
      - -config.file=/etc/config.yaml
      - -target=distributor
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      # - -runtime-config.file=/etc/overrides/overrides.yaml
      # - -log.level=warn
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4040/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  pyro-ingester: # Pyro
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - /mnt/Media/Monitoring/Configs/pyro/microservices-mode-profiles.yaml:/etc/config.yaml # Note: profiles use microservices-mode-profiles.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=ingester
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      - -log.level=warn
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  pyro-frontend: # Pyro
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - /mnt/Media/Monitoring/Configs/pyro/microservices-mode-profiles.yaml:/etc/config.yaml # Note: profiles use microservices-mode-profiles.yaml
    ports:
      - "4040"
    command:
      - -config.file=/etc/config.yaml
      - -target=query-frontend
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      - -log.level=warn
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  pyro-querier: # Pyro
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - /mnt/Media/Monitoring/Configs/pyro/microservices-mode-profiles.yaml:/etc/config.yaml # Note: profiles use microservices-mode-profiles.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=querier
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      - -log.level=warn
    networks:
      default:
        aliases:
          - pyroscope-memberlist
  
  pyro-scheduler: # Pyro
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - /mnt/Media/Monitoring/Configs/pyro/microservices-mode-profiles.yaml:/etc/config.yaml # Note: profiles use microservices-mode-profiles.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=query-scheduler
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      - -log.level=error
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  pyro-store-gateway: # Pyro
    depends_on:
      minio:
        condition: service_healthy
    image: *pyroscopeImage
    volumes:
      - /mnt/Media/Monitoring/Configs/pyro/microservices-mode-profiles.yaml:/etc/config.yaml # Note: profiles use microservices-mode-profiles.yaml
    command:
      - -config.file=/etc/config.yaml
      - -target=store-gateway
      - -memberlist.cluster-label=profiles-system
      - -memberlist.join=pyroscope-memberlist:7946
      - -log.level=error
    networks:
      default:
        aliases:
          - pyroscope-memberlist

  grafana: #All
    image: grafana/grafana:10.2.0
    hostname: grafana
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - /mnt/Media/Monitoring/Configs/grafana/grafana.ini:/etc/grafana-config/grafana.ini # All
      - /mnt/Media/Monitoring/Configs/grafana/dashboards:/var/lib/grafana/dashboards # All
      - /mnt/Media/Monitoring/Configs/grafana/provisioning:/etc/grafana/provisioning # All
      - /mnt/Media/Monitoring/Configs/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml # Metrics
    environment:
      - GF_LOG_LEVEL=error # All
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin_password} # All
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor # Tempo
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=agent:4317 # Tempo
      - GF_TRACING_OPENTELEMETRY_CUSTOM_ATTRIBUTES=cluster:docker-compose,namespace:monitoring # Tempo
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph # Pyro
      - GF_DIAGNOSTICS_PROFILING_ENABLED=true # Pyro
      - GF_DIAGNOSTICS_PROFILING_ADDR=0.0.0.0 # Pyro
      - GF_DIAGNOSTICS_PROFILING_PORT=6060 # Pyro
    ports:
      - "3000:3000"

  opentelemetry-collector:
    container_name: opentelemetry-collector
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./opentelemetry-collector/otel-config.yaml:/etc/otel-config.yaml
    command:
      - "--config=/etc/otel-config.yaml"