auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 300s # allow longer time span queries
  http_server_write_timeout: 300s # allow longer time span queries
  log_level: warn

common:
  compactor_address: loki
  path_prefix: /loki
  storage:
    s3:
      endpoint: minio:9000
      bucketnames: loki-data
      access_key_id: acester822
      secret_access_key: 228retseca
      insecure: true
      s3forcepathstyle: true

memberlist:
  join_members: [ loki-memberlist:7946 ]

ruler:
  storage:
    s3:
      bucketnames: loki-rules

schema_config:
  configs:
    - from: 2023-11-08
      store: tsdb
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      
frontend:
  max_outstanding_per_tenant: 2048 # default = 100]
  log_queries_longer_than: 20s
      
ingester:
  chunk_idle_period: 30m       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h            # All chunks will be flushed when they hit this age, default is 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0

query_range:
  parallelise_shardable_queries: false
  split_queries_by_interval: 0s
  align_queries_with_step: true

limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  per_stream_rate_limit: 512M
  cardinality_limit: 200000
  ingestion_burst_size_mb: 100000
  ingestion_rate_mb: 100000
  max_entries_limit_per_query: 10000000
  max_global_streams_per_user: 100000
  max_streams_per_user: 0
  max_label_value_length: 200480
  max_label_name_length: 100240
  max_label_names_per_series: 300

compactor:
  working_directory: /tmp/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 100

# -reporting.enabled=false
analytics:
 reporting_enabled: false
