auth_enabled: false

server:
  http_listen_port: 3100
  log_level: warn

common:
  compactor_address: loki
  path_prefix: /loki
  storage:
    s3:
      endpoint: minio:9000
      bucketnames: loki-data
      access_key_id: acester822
      secret_access_key: 228retseca
      insecure: true

memberlist:
  join_members: [ loki-memberlist:7946 ]

ruler:
  storage:
    s3:
      bucketnames: loki-rules

schema_config:
  configs:
    - from: 2023-11-08
      store: tsdb
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      
frontend:
      compress_responses: true
      
ingester:
      chunk_block_size: 262144
      chunk_encoding: gzip
      chunk_retain_period: 10m
      chunk_target_size: 0
      flush_check_period: 2m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
      max_chunk_age: 30m
      max_returned_stream_errors: 10
      max_transfer_retries: 0
      query_store_max_look_back_period: 0
      sync_min_utilization: 0
      sync_period: 0

query_range:
  parallelise_shardable_queries: false
  split_queries_by_interval: 0s
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m
  per_stream_rate_limit: 512M
  cardinality_limit: 200000
  ingestion_burst_size_mb: 100000
  ingestion_rate_mb: 100000
  max_entries_limit_per_query: 10000000
  max_global_streams_per_user: 100000
  max_streams_per_user: 0
  max_label_value_length: 200480
  max_label_name_length: 100240
  max_label_names_per_series: 300

compactor:
  working_directory: /tmp/compactor
  shared_store: s3

# -reporting.enabled=false
analytics:
 reporting_enabled: false
