analytics:
  reporting_enabled: false

storage:
  backend: s3
  s3:
    bucket_name: pyroscope-data
    endpoint: minio:9000
    access_key_id: admin
    secret_access_key: admin_password
    insecure: true
