auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: warn

common:
  compactor_address: loki
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      bucketnames: loki-data
      access_key_id: admin
      secret_access_key: admin_password
      insecure: true
      s3forcepathstyle: true

memberlist:
  join_members: [ loki-memberlist:7946 ]

ruler:
  storage:
    s3:
      bucketnames: loki-rules

schema_config:
  configs:
    - from: 2023-08-01
      store: tsdb
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true

query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true

compactor:
  working_directory: /tmp/compactor
  shared_store: s3

# -reporting.enabled=false
analytics:
 reporting_enabled: false
