auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: warn

common:
  compactor_address: http://compactor:3100
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      bucketnames: loki-data
      access_key_id: admin
      secret_access_key: admin_password
      insecure: true
      s3forcepathstyle: true

memberlist:
  join_members: [ loki-memberlist:7946 ]

frontend:
  scheduler_address: query-scheduler:9095
  tail_proxy_url: http://querier:3100
frontend_worker:
  scheduler_address: query-scheduler:9095

ruler:
  storage:
    s3:
      bucketnames: loki-rules

schema_config:
  configs:
    - from: 2023-08-01
      store: tsdb
      object_store: s3
      schema: v12
      index:
        prefix: loki_index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true

query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        ttl: 1h

compactor:
  shared_store: s3

# -reporting.enabled=false
analytics:
 reporting_enabled: false
