# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-system

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_dashboard_folder: "/dashboards/Mimir"

configMapGenerator:
- name: mimir-alertmanager-resources.json
  files:
  - dashboards_out/mimir-alertmanager-resources.json
- name: mimir-alertmanager.json
  files:
  - dashboards_out/mimir-alertmanager.json
- name: mimir-compactor-resources.json
  files:
  - dashboards_out/mimir-compactor-resources.json
- name: mimir-compactor.json
  files:
  - dashboards_out/mimir-compactor.json
- name: mimir-config.json
  files:
  - dashboards_out/mimir-config.json
- name: mimir-object-store.json
  files:
  - dashboards_out/mimir-object-store.json
- name: mimir-queries.json
  files:
  - dashboards_out/mimir-queries.json
- name: mimir-reads.json
  files:
  - dashboards_out/mimir-reads.json
- name: mimir-scaling.json
  files:
  - dashboards_out/mimir-scaling.json
- name: mimir-writes.json
  files:
  - dashboards_out/mimir-writes.json
- name: mimir-ruler.json
  files:
  - dashboards_out/mimir-ruler.json
- name: mimir-rollout-progress.json
  files:
  - dashboards_out/mimir-rollout-progress.json
- name: mimir-slow-queries.json
  files:
  - dashboards_out/mimir-slow-queries.json