server:
  http_listen_port: 3200
  log_level: warn

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        http:

memberlist:
  join_members: [ tempo-memberlist:7946 ]

metrics_generator:
  registry:
    external_labels:
      cluster: docker-compose
      namespace: monitoring
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://gateway:8080/api/v1/push
        send_exemplars: true
        headers:
          X-Scope-OrgID: "anonymous"

storage:
  trace:
    backend: s3                        # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
    s3:
      bucket: tempo-data                    # how to store data in s3
      endpoint: minio:9000
      access_key: acester822
      secret_key: 228retseca
      insecure: true
      # For using AWS, select the appropriate regional endpoint and region
      # endpoint: s3.dualstack.us-west-2.amazonaws.com
      # region: us-west-2

overrides:
  metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator
