usage_report:
  reporting_enabled: false

multitenancy_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  log_level: warn

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
    otlp:
      protocols:
        http:
        grpc:

memberlist:
  join_members: [ tempo-memberlist:7946 ]

compactor:
  ring:
    kvstore:
      store: memberlist

querier:
  frontend_worker:
    frontend_address: tempo:9095
    
storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: tempo-data
      endpoint: minio:9000
      access_key: acester822
      secret_key: 228retseca
      insecure: true