# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: false

# -usage-stats.enabled=false
usage_stats:
  enabled: false

server:
  http_listen_port: 8080
  grpc_listen_port: 9095
  log_level: warn

common:
  storage:
    backend: s3
    s3:
      endpoint:          minio:9000
      access_key_id:     acester822
      secret_access_key: 228retseca
      insecure:          true

memberlist:
  join_members: [ mimir-memberlist:7946 ]

ingester:
  ring:
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

blocks_storage:
  s3:
    bucket_name: mimir-data
  tsdb:
    dir: /data/ingester
    ship_interval: 1m
    block_ranges_period: [ 2h ]
    retention_period: 3h

ruler_storage:
  s3:
    bucket_name: mimir-rules

compactor:
  compaction_interval: 30s
  data_dir: /tmp/mimir-compactor
  cleanup_interval:    1m
  tenant_cleanup_delay: 1m

limits:
  native_histograms_ingestion_enabled: true