target: all,alertmanager

common:
  storage:
    backend: s3
    s3:
      endpoint:          minio:9000
      access_key_id:     acester822
      secret_access_key: 228retseca
      insecure:          true
      bucket_name: mimir-data
      
blocks_storage:
  storage_prefix: blocks
  tsdb:
    retention_period: 2h
    ship_interval: 5m
    dir: /data/mimir-ingester

memberlist:
  join_members: [ mimir-memberlist:7946 ]

ruler:
  rule_path: /data/mimir-rules
  alertmanager_url: http://gateway:8080/alertmanager
  ring:
    # Quickly detect unhealthy rulers to speed up the tutorial.
    heartbeat_period: 2s
    heartbeat_timeout: 10s

alertmanager:
  data_dir: /data/mimir-alertmanager
  enable_api: true
  fallback_config_file: /etc/alertmanager-fallback.yml
  external_url: /alertmanager

server:
  http_listen_port: 8080
  log_level: warn
