ingester_limits: # limits that each ingester replica enforces
  max_ingestion_rate: 20000000
  max_series: 1500000000
  max_tenants: 1000000
  max_inflight_push_requests: 3000000

distributor_limits: # limits that each distributor replica enforces
  max_ingestion_rate: 20000000
  max_inflight_push_requests: 30000000
  max_inflight_push_requests_bytes: 5000000000

overrides:
  anonymous: # limits for anonymous that the whole cluster enforces
    # ingestion_tenant_shard_size: 9
    max_global_series_per_user: 300000000
    max_fetched_series_per_query: 100000000